### PR TITLE
Jan 2021 updates

### PR DESCRIPTION
**Pull request by brendanc**
Updates to:

 - update Litmus result id to a long to accommodate upcoming api changes
 - remove page testing artifacts that are no longer supported by the api

### CODE REVIEW

**Review by carlosneninger — APPROVED** [review]
✔️

**Comment by Julie-House** [comment]
You've missed a couple of places. GetEmailTest and GetEmailTestAsync are still taking an int. And the EmailTest object has the Id as int.

**Comment by brendanc** [comment]
@Julie-House The email test ids are remaining ints.  Only the result ids are changing to longs.  Each test contains several results (hence why the numbers are significantly larger).

This api kind of obfuscates the underlying data structure a bit but the data structure is:

EmailTest (int id) [represented by [EmailTest.cs](https://github.com/litmus/previews-api-client/blob/master/Litmus/Apis/Previews/Models/EmailTest.cs)]
- Result (long id) [represented by [TestingApplication.cs](https://github.com/litmus/previews-api-client/blob/master/Litmus/Apis/Previews/Models/TestingApplication.cs)]
- Result (long id) [represented by [TestingApplication.cs](https://github.com/litmus/previews-api-client/blob/master/Litmus/Apis/Previews/Models/TestingApplication.cs)]
- Result (long id) [represented by [TestingApplication.cs](https://github.com/litmus/previews-api-client/blob/master/Litmus/Apis/Previews/Models/TestingApplication.cs)])
- etc...

**Comment by Julie-House** [comment]
@brendanc Thanks! it wasn't made clear that it was the individual tests, and not the email test that was changing.

**Pull request merged**
